name: ml-env
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - numpy>=1.21.0  # Higher version requirement
  - pandas>=1.4.0
  - scikit-learn>=0.24.0
  - tensorflow-gpu>=2.6.0  # GPU version
  - pytorch>=1.10.0  # Different package name
  - cudatoolkit=11.3
  - transformers>=4.5.0
  - jax>=0.3.0  # Different version
  - jaxlib>=0.3.0
  - datasets>=2.0.0  # Higher version
  - tokenizers>=0.12.0
  - tqdm>=4.62.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.2
  - pillow>=9.0.0
  - pip:
    - tensorflow-probability>=0.14.0
    - torch-scatter>=2.0.9
